name: Tests
"on":
  pull_request: {}
  push:
    branches:
    - main
jobs:
  unit:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
        cache-dependency-path: go.sum
    - name: Install richgo
      run: go install -ldflags="-s -w" github.com/kyoh86/richgo@latest
    - name: Run Tests
      run: richgo test -v ./... -coverprofile cover.out
      env:
        RICHGO_FORCE_COLOR: "1"
    - uses: codecov/codecov-action@v4
