name: Tests
"on":
  pull_request: {}
  push:
    branches:
    - main
jobs:
  unit:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        path: ${{ env.HOME }}/go/pkg/mod
        restore-keys: ${{ runner.os }}-go-
    - uses: actions/setup-go@v2
      with:
        go-version: "1.16"
    - name: Install richgo
      run: GO111MODULE=on go get -u -ldflags="-s -w" github.com/kyoh86/richgo
    - name: Run Tests
      run: richgo test -v ./... -coverprofile cover.out
      env:
        RICHGO_FORCE_COLOR: "1"
    - name: Report coverage
      run: bash <(curl -s https://codecov.io/bash)
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_API_TOKEN }}
